image: registry.gitlab.com/gitlab-org/release-cli:latest

cache:
  paths:
    - node_modules

before_script:
  - apk update
  - apk add nodejs build-base npm ruby make ruby-dev git asciidoctor curl ghostscript
  - gem install asciidoctor
  - gem install asciidoctor-pdf
  - gem install asciidoctor-diagram
  - gem install asciidoctor-bibtex
  - gem install coderay
  - gem install rouge
  - gem install pygments.rb
  - gem install json
  - gem install rghost
  - npm i npm@latest -g
  - npm install wavedrom-cli
  - PATH="$PATH:node_modules/.bin/"

job:
  script:
    - make
  artifacts:
    paths:
      - "*.pdf"

release_job:
  rules:
    - if: $CI_COMMIT_TAG
    
  script:
    - make
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file *.pdf "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/my_package/${CI_COMMIT_TAG}/bitmanip-${CI_COMMIT_TAG}.pdf"'
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
         --assets-link "{\"name\":\"pdf\",\"url\":\"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/my_package/${CI_COMMIT_TAG}/bitmanip-${CI_COMMIT_TAG}.pdf\"}"
