name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Ubuntu packages
      run: |
        sudo apt-get update
        sudo apt install nodejs build-base npm ruby make ruby-dev git asciidoctor curl
        sudo gem install asciidoctor
        sudo gem install asciidoctor-pdf
        sudo gem install asciidoctor-diagram
        sudo gem install asciidoctor-bibtex
        sudo gem install asciidoctor-mathematical
      
    - name: Build
      run: make

